import enkinex_odcs.iam.team

CeastWoodMember = team.TeamMember {
    username = "ceastwood"
    role = "Data Scientist"
    dateIn = "2022-08-02"
    dateOut: "2022-10-01"
    replacedByUsername = "mhopper"
}

MHopperMember = team.TeamMember {
    username = "mhopper"
    role = "Data Scientist"
    dateIn = "2022-10-01"
}

DaustinMember = team.TeamMember {
    username = "daustin"
    role = "Owner"
    description = "Keeper of the grail"
    dateIn = "2022-10-01"
}
